baseURL = 'https://pkchemlab.github.io/The-EXCITED-State/' 
languageCode = 'zh-cn'
title = "The EXCITED State"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # 跟随系统深色模式
    ShowReadingTime = true # 显示阅读时间
    ShowShareButtons = true # 显示分享按钮

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 3